### ISSUE TITLE
Missing dataset for pretraining

### ISSUE THREAD

**Issue by juxingyiwan** [UX-Decoder/LLaVA-Grounding#10]
We are really interested in your impressive work and want to train the model from scratch. Unfortunately, we didn't find 'cap600k_brackets_all.json' and corresponding image folder. Could you please release links for the pretrain data?

Thank you!

**Comment by HaoZhang534** [comment]
Hi, I will release the data soon.

**Comment by HaoZhang534** [comment]
@juxingyiwan We have released the data

**Comment by juxingyiwan** [comment]
Dear authors, sorry to bother you again. Regarding your work LLaVA Grounding, I am confused about the image folder parameter "/ConceptualCaptionsFiltered/" in the first training stage. Are all the images from the datasets used in the first training stage mentioned in the paper included in this folder?


Best regards.




为什么没有昵称呢
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "UX-Decoder/LLaVA-Grounding"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月22日(星期一) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [UX-Decoder/LLaVA-Grounding] Missing dataset for pretraining (Issue #10)





 
@juxingyiwan We have released the data
