### ISSUE TITLE
The trouble of visual prompt

### ISSUE THREAD

**Issue by Vilonge** [UX-Decoder/LLaVA-Grounding#11]
Thanks for the open source!

I set up the visual prompt based on your video tutorial, but got different results. The result will place the entire image in the bbox.

![image](https://github.com/UX-Decoder/LLaVA-Grounding/assets/89585131/31999261-cb59-4b6f-9b44-e1b6ca918bdf)

**Comment by HaoZhang534** [comment]
Can you use clear history and re-try the visual prompt?
