### ISSUE TITLE
Visual Grounding Prompt

### ISSUE THREAD

**Issue by lxiaohaung** [UX-Decoder/LLaVA-Grounding#4]
when I use what is the bounding box of ......, the model can't give me the box.So what prompt should I use?

**Comment by lxiaohaung** [comment]
I want get the bounding box of the object.

**Comment by HaoZhang534** [comment]
> I want get the bounding box of the object.

You can refer to the tutorial video in the demo link where you can use the question template to ask and the model will output a grounded response.

**Comment by lxiaohaung** [comment]
In fact, I want to get the coordinates of the bounding box，like[a,b,c,d]

**Comment by Wuwenji18** [comment]
> 其实我想得到边界框的坐标，比如[a，b，c，d]

Same question,have you salve the problem?

**Comment by Wuwenji18** [comment]
> > 我想获取对象的边界框。
> 
> 您可以参考演示链接中的教程视频，您可以在其中使用问题模板提问，模型将输出接地气的回答。

The link of dimo can not opened.
